import type { GuidedStepDefinition, GuidedStepId } from "./guidedTypes";

export const GUIDED_TOTAL_DISPLAYED_STEPS = 13;

export const GUIDED_STEPS = [
  {
    id: "a",
    levelNumber: 1,
    partLabel: "Level 1",
    title: "Learn A",
    introTitle: "Find A",
    playTitle: "Find A",
    targetNotes: ["A"],
    ghostAnchors: null,
    targetCount: 8,
    durationMs: 5_000,
    introCopy: "Find A across the fretboard.",
    previewCopy: "Take a quick look. You'll find them yourself next.",
    completionCopy: "A is starting to feel familiar.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 1,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "bc-assisted",
    levelNumber: 2,
    partLabel: "Level 2A",
    title: "Learn B + C with help",
    introTitle: "Learn B + C with help",
    playTitle: "Find B + C",
    targetNotes: ["B", "C"],
    ghostAnchors: { B: "A", C: "A" },
    targetCount: 8,
    durationMs: 4_250,
    introCopy: "Use the faint A to locate B and C. Only B and C will fall.",
    previewCopy: "See B and C beside the A notes you already know.",
    completionCopy: "B and C are joining your mental map.",
    isAssisted: true,
    isFinalRepeatable: false,
    stepNumber: 2,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "bc-unassisted",
    levelNumber: 2,
    partLabel: "Level 2B",
    title: "Find B + C",
    introTitle: "Find B + C",
    playTitle: "Find B + C",
    targetNotes: ["B", "C"],
    ghostAnchors: null,
    targetCount: 10,
    durationMs: 4_000,
    introCopy: "Now find B and C without the A hint.",
    previewCopy: "They are one fret apart. Take a quick look.",
    completionCopy: "B and C are getting faster.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 3,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "abc-mix",
    levelNumber: 2,
    partLabel: "Level 2C",
    title: "Mix A + B + C",
    introTitle: "Mix A + B + C",
    playTitle: "Mix A + B + C",
    targetNotes: ["A", "B", "C"],
    ghostAnchors: null,
    targetCount: 12,
    durationMs: 3_800,
    introCopy: "Mix A, B, and C together.",
    previewCopy: "Review A, B, and C across the fretboard.",
    completionCopy: "A, B, and C are becoming one group.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 4,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "d",
    levelNumber: 3,
    partLabel: "Level 3",
    title: "Learn D",
    introTitle: "Learn D",
    playTitle: "Find D",
    targetNotes: ["D"],
    ghostAnchors: null,
    targetCount: 8,
    durationMs: 3_750,
    introCopy: "Find D across the fretboard.",
    previewCopy: "See D across the fretboard.",
    completionCopy: "D is becoming part of the pattern.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 5,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "ef-assisted",
    levelNumber: 4,
    partLabel: "Level 4A",
    title: "Learn E + F with help",
    introTitle: "Learn E + F with help",
    playTitle: "Find E + F",
    targetNotes: ["E", "F"],
    ghostAnchors: { E: "D", F: "D" },
    targetCount: 8,
    durationMs: 3_600,
    introCopy: "Use the faint D to locate E and F. Only E and F will fall.",
    previewCopy: "See E and F beside the D notes you already know.",
    completionCopy: "E and F are joining your mental map.",
    isAssisted: true,
    isFinalRepeatable: false,
    stepNumber: 6,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "ef-unassisted",
    levelNumber: 4,
    partLabel: "Level 4B",
    title: "Find E + F",
    introTitle: "Find E + F",
    playTitle: "Find E + F",
    targetNotes: ["E", "F"],
    ghostAnchors: null,
    targetCount: 10,
    durationMs: 3_500,
    introCopy: "Now find E and F without the D hint.",
    previewCopy: "See E and F across the fretboard.",
    completionCopy: "E and F are getting faster.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 7,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "def-mix",
    levelNumber: 4,
    partLabel: "Level 4C",
    title: "Mix D + E + F",
    introTitle: "Mix D + E + F",
    playTitle: "Mix D + E + F",
    targetNotes: ["D", "E", "F"],
    ghostAnchors: null,
    targetCount: 12,
    durationMs: 3_400,
    introCopy: "Mix D, E, and F together.",
    previewCopy: "Review D, E, and F across the fretboard.",
    completionCopy: "D, E, and F are becoming one group.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 8,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "bcef-assisted",
    levelNumber: 5,
    partLabel: "Level 5A",
    title: "Connect both groups with help",
    introTitle: "Connect both groups with help",
    playTitle: "Find B + C + E + F",
    targetNotes: ["B", "C", "E", "F"],
    ghostAnchors: { B: "A", C: "A", E: "D", F: "D" },
    targetCount: 12,
    durationMs: 3_300,
    introCopy: "Connect both note groups. A helps with B/C; D helps with E/F.",
    previewCopy: "Review B, C, E, and F with anchor hints.",
    completionCopy: "Both groups are starting to connect.",
    isAssisted: true,
    isFinalRepeatable: false,
    stepNumber: 9,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "bcef-unassisted",
    levelNumber: 5,
    partLabel: "Level 5B",
    title: "Connect both groups",
    introTitle: "Connect both groups",
    playTitle: "Find B + C + E + F",
    targetNotes: ["B", "C", "E", "F"],
    ghostAnchors: null,
    targetCount: 14,
    durationMs: 3_200,
    introCopy: "Connect B, C, E, and F without hints.",
    previewCopy: "Review B, C, E, and F across the fretboard.",
    completionCopy: "Both groups are connecting faster.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 10,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "abcdef-mix",
    levelNumber: 5,
    partLabel: "Level 5C",
    title: "Mix A through F",
    introTitle: "Mix A through F",
    playTitle: "Mix A through F",
    targetNotes: ["A", "B", "C", "D", "E", "F"],
    ghostAnchors: null,
    targetCount: 18,
    durationMs: 3_100,
    introCopy: "Mix A through F together.",
    previewCopy: "Review A through F across the fretboard.",
    completionCopy: "A through F are becoming one map.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 11,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "g",
    levelNumber: 6,
    partLabel: "Level 6A",
    title: "Learn G",
    introTitle: "Learn G",
    playTitle: "Find G",
    targetNotes: ["G"],
    ghostAnchors: null,
    targetCount: 8,
    durationMs: 3_000,
    introCopy: "Find G across the fretboard.",
    previewCopy: "See G across the fretboard.",
    completionCopy: "G is joining your fretboard map.",
    isAssisted: false,
    isFinalRepeatable: false,
    stepNumber: 12,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
  {
    id: "abcdefg-mix",
    levelNumber: 6,
    partLabel: "Level 6B",
    title: "Mix all natural notes",
    introTitle: "Mix all natural notes",
    playTitle: "Mix A through G",
    targetNotes: ["A", "B", "C", "D", "E", "F", "G"],
    ghostAnchors: null,
    targetCount: 21,
    durationMs: 2_900,
    introCopy: "Mix all seven natural notes.",
    previewCopy: "Review A through G across the fretboard.",
    completionCopy: "All natural notes are in play.",
    isAssisted: false,
    isFinalRepeatable: true,
    stepNumber: 13,
    totalDisplayedSteps: GUIDED_TOTAL_DISPLAYED_STEPS,
  },
] as const satisfies readonly GuidedStepDefinition[];

export const DEFAULT_GUIDED_STEP_ID: GuidedStepId = "a";

const BY_ID = new Map(GUIDED_STEPS.map((step) => [step.id, step]));

export function getGuidedStepById(stepId: GuidedStepId): GuidedStepDefinition {
  const step = BY_ID.get(stepId);
  if (!step) {
    throw new Error(`Unknown Guided step: ${stepId}`);
  }
  return step;
}

export function getGuidedStepIndex(stepId: GuidedStepId): number {
  return GUIDED_STEPS.findIndex((step) => step.id === stepId);
}

export function isGuidedStepId(value: unknown): value is GuidedStepId {
  return typeof value === "string" && BY_ID.has(value as GuidedStepId);
}

export function getGuidedStepIds(): readonly GuidedStepId[] {
  return GUIDED_STEPS.map((step) => step.id);
}

export function getGuidedGhostAnchor(
  step: GuidedStepDefinition,
  targetNote: string,
): string | null {
  if (!step.ghostAnchors) return null;
  return step.ghostAnchors[targetNote as keyof typeof step.ghostAnchors] ?? null;
}
